<a href="https://colab.research.google.com/github/Henry6833/Henry6833.github.io/blob/main/Milestone1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Students' perception of Artificial Intelligence effects on Cognitive Engagement

---

#Project Goal

Our group, formed by Randall Herrera and Henry Mulvihill will be investigating multiple different student's insights on how the use of Ai affects their cognitive engagement. We want to showcase the student's learning behaviors with ai and their feeback on congitive engagement using it. We emphasized searching for survey datasets that asked students the following: frequency usage with AI tools, perceived reliance on it, their perceived effects on critical thinking, and background about the student. We have found two survey datasets that give great measurement and feedback for this project.

#The DataSets

Our main dataset, [AI Dependency and Academic Vulnerability](https://www.kaggle.com/datasets/mdjhirulislam/ai-dependency-and-academic-vulnerability), contains over one thousand college students responses from a variey of questions pertaining to how they use Ai in academics. The main topics these questions answer are how dependent students are to Ai for learning and if Ai's help with cognitive offload is harmful. Our last dataset, [GenAI Impact on Critical Thinking:BD Study](https://www.kaggle.com/datasets/mehedirafidsm/genai-impact-on-critical-thinking-bd-study), contains four hundred responses from college students. These questions asked the students to self evaluate their reliance on Ai, how frequently they use it, and a 1-5 agreement scale.

#Collaboration Plan

We decided to meet up for 15 minutes after every Data Science class to speak catch up on our project ideas where we would refine, expand, and assist one another's ideas. We also would meet via Discord every Tuesday or Saturday to assist in the changes made to the project. Outside of meetings we would commit changes we've made to our github repository. After someone made changes they would text the other about the more polished or expanded version of the project.

In [1]:
import pandas as pd
import numpy as np
import kagglehub
import os
# Download latest version
path = kagglehub.dataset_download("mdjhirulislam/ai-dependency-and-academic-vulnerability")
print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/mdjhirulislam/ai-dependency-and-academic-vulnerability/1.archive...

100%|██████████| 11.7k/11.7k [00:00<00:00, 15.1MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/mdjhirulislam/ai-dependency-and-academic-vulnerability/versions/1

By importing the os module that is built-in in Python, we can interact with the operating system: files, folders, and paths. Now, we might want to show what the folder that kagglehub created contains. os.listdir(path) allows us to see everything inside that folder. Is the code version or running !ls.

In [2]:
%cd /root/.cache/kagglehub/datasets/mdjhirulislam/ai-dependency-and-academic-vulnerability/versions/1
!ls

/root/.cache/kagglehub/datasets/mdjhirulislam/ai-dependency-and-academic-vulnerability/versions/1
'AI Dependency and Academic Vulnerability in Higher Education A Survey Dataset from Bangladesh.csv'

In [3]:
# Raw urls of the datasets obtained from the data/ folder in the GitHub source repository
url_dataset_1 = "https://raw.githubusercontent.com/Henry6833/Henry6833.github.io/refs/heads/main/data/Survey_Data_GenAI_Critical_Thinking_Bangladesh.csv"

In [4]:
Bangladesh_S = pd.read_csv(url_dataset_1)
Bangladesh_S.head()

,Year,Gender,Department,Usage_Freq,Primary_Tool,RelyOnAI_Answers,ReducesCritical,LimitsSkills,MemoryRetentionDrop,CT1_IndependentAnalysis,...,PROD2_TaskCompletion,PROD3_ConceptClarity,CGPA,CT_Composite,Dependency_Composite,Benefit_Composite,Cluster,CT_Sum,Dependency_Sum,Benefit_Sum
0,4,Male,BBA,Often,Gemini,3,3,2,2,2,...,5,4,3.50,1.75,2.50,4.6,Balanced / Moderate Users,7,10,23
1,2,Female,CSE,Often,ChatGPT,4,4,4,5,4,...,3,2,2.90,4.00,4.25,2.4,Highly Dependent / At-Risk Users,16,17,12
2,4,Female,Civil,Daily,Microsoft Copilot,4,4,5,5,4,...,1,2,3.58,3.25,4.50,1.6,Highly Dependent / At-Risk Users,13,18,8
3,3,Male,BBA,Daily,ChatGPT,5,5,5,5,3,...,4,4,3.35,2.50,5.00,3.8,"Strategic Users (High Reliance, High Benefit)",10,20,19
4,1,Prefer not to say,CSE,Daily,ChatGPT,4,3,3,2,4,...,4,5,3.29,4.00,3.00,4.4,"Strategic Users (High Reliance, High Benefit)",16,12,22

This code snipped allowed us to download another dataset from Kaggle's API. This dataset is about AI dependency and Vulnerability in Higher Education.

In [5]:
Bangladesh_L = pd.read_csv(os.path.join(path, "AI Dependency and Academic Vulnerability in Higher Education A Survey Dataset from Bangladesh.csv"))
Bangladesh_L.head()

,Gender,Age,Name of University,Academic Level,Current CGPA,Daily AI Usage Time,I verify AI-generated information before using it in academic work.,I can study and complete tasks effectively without any AI support.,My first instinct for any academic doubt is to ask an AI rather than checking books or notes.,I find it harder to recall information that I have previously generated using AI.,"When using AI, I prioritize completing assignments quickly rather than fully understanding the subject matter.",I often use AI-generated responses without making any major modifications.,I feel less confident in my writing and analytical skills when I am not using AI.,My critical thinking ability has weakened due to reliance on AI tools.,I often submit academic work without fully understanding the content generated by AI.
0,Male,24-26,Jahangirnagar University,Master's,3.01-3.50,1-3 hours,Disagree,Disagree,Strongly Agree,Agree,Neutral,Agree,Strongly Agree,Strongly Agree,Agree
1,Male,20-23,Daffodil International University,Undergraduate,2.51-3.00,1-3 hours,Strongly Agree,Agree,Neutral,Agree,Disagree,Strongly Agree,Agree,Agree,Strongly Agree
2,Female,20-23,Daffodil International University,Undergraduate,3.01-3.50,1-3 hours,Agree,Neutral,Agree,Disagree,Agree,Disagree,Agree,Agree,Disagree
3,Female,20-23,Daffodil International University,Undergraduate,3.01-3.50,1-3 hours,Agree,Neutral,Neutral,Disagree,Agree,Disagree,Neutral,Strongly Agree,Agree
4,Female,20-23,Primeasia University,Undergraduate,Above 3.50,Less than 1 hour,Agree,Neutral,Neutral,Disagree,Agree,Neutral,Neutral,Disagree,Disagree