<a href="https://colab.research.google.com/github/Henry6833/Henry6833.github.io/blob/main/Milestone1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Students' own perception on the effects of Artificial Intelligence on their critical thinking capabilities.

---

#Project Goal

Our group, formed by Randall Herrera and Henry Mulvihill will be investigating multiple different student's insights on how the use of Artificial Intelligence affects their critical thinking capabilities. We emphasized searching for survey datasets that asked students the following: frequency usage with AI tools, perceived reliance on it, their perceived effects on critical thinking, and background about the student. We have found two survey datasets that give great measurement and feedback for this project.

#Collaboration Plan

We decided to meet up for 15 minutes after every Data Science class to speak catch up on our project ideas where we would refine, expand, and assist one another's ideas. We also would meet via Discord every Tuesday or Saturday to assist in the changes made to the project. !! Will expand more later when milestone finished

In [5]:
import pandas as pd
import numpy as np

In [7]:
# Raw urls of the datasets obtained from the data/ folder in the GitHub source repository
url_dataset_1 = "https://raw.githubusercontent.com/Henry6833/Henry6833.github.io/refs/heads/main/data/Critical_Thinking_and_Problem_Solving_Assessment_in_the_AI_Era.csv"
url_dataset_2 = "https://raw.githubusercontent.com/Henry6833/Henry6833.github.io/refs/heads/main/data/Survey_Data_GenAI_Critical_Thinking_Bangladesh.csv"

In [8]:
Bangladesh_L = pd.read_csv(url_dataset_1)
Bangladesh_S = pd.read_csv(url_dataset_2)

In [11]:
Bangladesh_L.head()

,Timestamp,Age:,Educational Background:,Current Occupation:,Years of regular AI tool usage:,Which AI tools do you use regularly?,Primary reason for using AI:,"When faced with a difficult problem, what do you usually do first?","Before using AI tools regularly, how confident were you in solving complex problems?","After using AI tools regularly, how confident are you now?",...,"If it takes 10 workers 10 days to complete a task,\nhow many days will it take 5 workers to complete the same task?",A number multiplied by 4 and then reduced by 6 gives 26. What is the number?,A doctor gives you 3 pills and tells you to take one pill every 30 minutes. How long will it take to finish all the pills?,How mentally difficult was Section A?,Did you feel mentally tired after solving these?,A car travels 60 km in 1 hour.\nHow far will it travel in 30 minutes at the same speed?,"If 5 machines make 5 products in 5 minutes,\nhow many minutes will 100 machines take to make 100 products?",Did you use AI in Section B?,"If yes, what did AI mostly do?",Do you believe AI is strengthening or weakening human thinking? Why? (Must Answer Your Thoughts)
0,2/6/2026 23:15:48,24–26,Science / Engineering,Freelancer / Self-employed,More than 2 years,"ChatGPT, Gemini, DeepSeek","Learning concepts, Solving problems, Generatin...","Think briefly, then use AI",Confident,Very confident,...,20,8,90 minutes,Very easy,No,30km,5 minutes,NO,Explained the logic,No comment
1,2/6/2026 23:26:49,27–30,Arts / Humanities,Freelancer / Self-employed,6–12 months,ChatGPT,"Learning concepts, Solving problems, Generatin...","Think briefly, then use AI",Neutral,Confident,...,20,8,1 hour,Very easy,No,30 km,5 minutes,NO,Both,It varies person to person.
2,2/6/2026 23:53:08,24–26,Science / Engineering,Student,1–2 years,"ChatGPT, Other","Learning concepts, Solving problems, Generatin...","Think briefly, then use AI",Not confident,Very confident,...,20 days,5,1 hour,Very easy,No,30km,5 minutes,NO,NaN,Its strengthing in some sector weakening in so...
3,2/7/2026 1:53:59,24–26,Science / Engineering,Student,1–2 years,"ChatGPT, Gemini","Learning concepts, Solving problems, Generatin...",Try to solve it myself,Confident,Neutral,...,20days,8,1hour,Very easy,Slightly,30km,5min,NO,NaN,"In some of the cases, I think it is weakening ..."
4,2/7/2026 11:04:38,21–23,Science / Engineering,Student,More than 2 years,"ChatGPT, Gemini, Grok","Learning concepts, Solving problems, Generatin...",Try to solve it myself,Not confident,Confident,...,20,8,90 mins,Very easy,No,30km,5 mins,NO,NaN,using AI immediately for a problem is not good...

In [12]:
Bangladesh_S.head()

,Year,Gender,Department,Usage_Freq,Primary_Tool,RelyOnAI_Answers,ReducesCritical,LimitsSkills,MemoryRetentionDrop,CT1_IndependentAnalysis,...,PROD2_TaskCompletion,PROD3_ConceptClarity,CGPA,CT_Composite,Dependency_Composite,Benefit_Composite,Cluster,CT_Sum,Dependency_Sum,Benefit_Sum
0,4,Male,BBA,Often,Gemini,3,3,2,2,2,...,5,4,3.50,1.75,2.50,4.6,Balanced / Moderate Users,7,10,23
1,2,Female,CSE,Often,ChatGPT,4,4,4,5,4,...,3,2,2.90,4.00,4.25,2.4,Highly Dependent / At-Risk Users,16,17,12
2,4,Female,Civil,Daily,Microsoft Copilot,4,4,5,5,4,...,1,2,3.58,3.25,4.50,1.6,Highly Dependent / At-Risk Users,13,18,8
3,3,Male,BBA,Daily,ChatGPT,5,5,5,5,3,...,4,4,3.35,2.50,5.00,3.8,"Strategic Users (High Reliance, High Benefit)",10,20,19
4,1,Prefer not to say,CSE,Daily,ChatGPT,4,3,3,2,4,...,4,5,3.29,4.00,3.00,4.4,"Strategic Users (High Reliance, High Benefit)",16,12,22